#!/bin/sh

cat <<'EOF'
# The UNIVERSE defines an execution environment. You will almost always use VANILLA. 
Universe = vanilla 

# EXECUTABLE is the program your job will run It's often useful 
# to create a shell script to "wrap" your actual work. 
Executable = luminance

# ERROR and OUTPUT are the error and output channels from your job
# that HTCondor returns from the remote host.
Error = log/job.error.$(Cluster)-$(Process) 
Output = log/job.output.$(Cluster)-$(Process) 

# The LOG file is where HTCondor places information about your 
# job's status, success, and resource consumption. 
Log = job.log

# Read job stdin from here:
Input = manifest.txt

# We need this exec to decode the JPEG files into RGB 3-tuples. Ideally
# we might include a python module for it, but this is a simple demo.
# djpeg is compiled statically for portability across platforms.
Transfer_input_files = djpeg

# +ProjectName is the name of the project reported to the OSG accounting system
+ProjectName="ConnectTrain"

# QUEUE is the "start button" - it launches any jobs that have been 
# specified thus far. 
#Queue 1
EOF

# We have about 5500 photos to analyze. Block them off by 200s and
# submit enough jobs to handle.
chunk=${1-200}
max=${2-5600}

i=0
while [ $i -lt $max ]; do
	echo Arguments = $i $chunk
	echo Queue 1
	echo
	i=$(($i + $chunk))
done
